---
- name: Sync contents to s3 bucket
  community.aws.s3_sync:
    bucket: email-signature-generator-{{ system_environment }}
    file_root: content
    file_change_strategy: date_size
    storage_class: STANDARD
  register: s3_upload

- name: Invalidate Cloudfront cache if content changed
  community.aws.cloudfront_invalidation:
    alias: '{{ site_url }}'
    target_paths:
      - /*
  when: s3_upload.changed
